@echo off
rem ====================================================================
rem buildDbDo.cmd - build script for DbDo.exe (v1.0.44 and later).
rem
rem Compiles two assemblies with the stock .NET Framework compilers:
rem
rem   1. DbDo.dll -- JScript .NET support module, compiled from
rem      DbDo.js by jsc.exe. Used by the Help > Invoke Snippet
rem      feature to run user-written .js snippets against the running
rem      DbDoForm and DbDoManager.
rem
rem   2. DbDo.exe -- the main WinForms application, compiled from
rem      DbDo.cs by csc.exe. The exe calls DbDo.JS.runScript(...)
rem      via reflection (Assembly.LoadFrom + GetType + GetMethod),
rem      so csc.exe does NOT take /reference:DbDo.dll at compile time.
rem      Avoiding the compile-time reference also prevents an assembly-
rem      name collision at load time: the EXE is also named DbDo,
rem      so Assembly.Load("DbDo") would resolve to DbDo.exe instead
rem      of DbDo.dll. We use Assembly.LoadFrom with the full path to
rem      DbDo.dll for an unambiguous load.
rem
rem ---------- Why bare compilers, not MSBuild + NuGet ----------
rem
rem v1.0.42 and v1.0.43 used MSBuild + NuGet to pull in the Roslyn
rem C# scripting package (Microsoft.CodeAnalysis.CSharp.Scripting),
rem which dragged about a dozen transitive DLLs (~25-30 MB) into the
rem DbDo install folder. That worked but was disproportionate to the
rem feature it enabled. v1.0.44 follows EdSharp's model: JScript .NET
rem via jsc.exe. JScript .NET ships with every .NET 4.x install in the
rem v4.0.30319 framework folder; no NuGet package, no shipped DLLs,
rem no binding redirects. The whole scripting subsystem is one ~10 KB
rem DbDo.dll plus the snippet folder.
rem
rem ---------- Compiler search order ----------
rem
rem csc.exe AND jsc.exe both live next to each other under either:
rem   - Visual Studio / Build Tools Roslyn folder (Roslyn-era csc.exe)
rem   - %SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\
rem
rem The Framework folder is present on every Windows install with
rem .NET 4.x, so the build works without Visual Studio. We prefer the
rem Visual Studio csc.exe when available for better diagnostics but
rem always use the Framework jsc.exe (no Roslyn equivalent for JScript).
rem ====================================================================

setlocal enableextensions enabledelayedexpansion

pushd "%~dp0"

set "log=buildDbDo.log"
echo DbDo build log > "!log!"
echo Started at %DATE% %TIME% (Pacific time, Seattle) >> "!log!"
echo Script directory: %~dp0 >> "!log!"
echo Working directory: %CD% >> "!log!"
echo. >> "!log!"

rem ---- check source files ----
if not exist "DbDo.cs"  goto :no_dbdo_cs
if not exist "DbDo.js"  goto :no_dbdo_js
goto :have_sources

:no_dbdo_cs
echo ERROR: DbDo.cs not found. >> "!log!"
echo ERROR: DbDo.cs not found in script directory.
popd
exit /b 1

:no_dbdo_js
echo ERROR: DbDo.js not found. >> "!log!"
echo ERROR: DbDo.js not found in script directory.
popd
exit /b 1

:have_sources
echo Found: DbDo.cs, DbDo.js >> "!log!"

rem ---- version: generated from DbDo_setup.iss (the SINGLE source of truth) ----
rem The version number lives in exactly ONE place: AppVersion in DbDo_setup.iss.
rem This step reads it and generates Version.cs, which defines BuildVersion.Version;
rem DbDo.cs uses that constant instead of hard-coding a number.  Nothing can drift,
rem so no cross-check is needed: the .exe and the installer are compiled from the
rem same value by construction.  Version.cs is generated output -- do not edit it,
rem and keep it out of source control.
set "issVer="
for /f tokens^=2^ delims^=^" %%v in ('findstr /r /c:"^#define AppVersion" "DbDo_setup.iss" 2^>nul') do if not defined issVer set "issVer=%%v"
if not defined issVer for /f "tokens=2 delims==" %%v in ('findstr /r /c:"^AppVersion=" "DbDo_setup.iss" 2^>nul') do if not defined issVer set "issVer=%%v"
rem strip any stray spaces (a version number never contains one)
if defined issVer set "issVer=!issVer: =!"
if not defined issVer (
  echo ERROR: could not read AppVersion from DbDo_setup.iss.
  echo ERROR: could not read AppVersion from DbDo_setup.iss. ^>^> "!log!"
  popd ^& exit /b 1
)
> Version.cs echo // Generated by buildDbDo.cmd from AppVersion in DbDo_setup.iss.  Do not edit; do not commit.
>> Version.cs echo public static class BuildVersion
>> Version.cs echo {
>> Version.cs echo     public const string Version = "!issVer!";
>> Version.cs echo }
echo Version: !issVer!
echo Version: !issVer! >> "!log!"

rem ---- locate csc.exe ----
rem Prefer Roslyn from Visual Studio Build Tools / VS 2022/2019, fall
rem back to legacy csc bundled with the Framework runtime.
set "csc="
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe" set "csc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not defined csc if exist "%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\csc.exe" set "csc=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\csc.exe"

if defined csc goto :have_csc
echo ERROR: No csc.exe found. >> "!log!"
echo ERROR: No csc.exe found. Repair .NET Framework or install VS Build Tools.
popd
exit /b 1

:have_csc
echo C# compiler: !csc! >> "!log!"

rem ---- auto-bump the version, then sync the installer ----
rem Every build advances the version so each GitHub release is newer
rem than the installed copy -- which is what F11 compares. The next
rem number is derived from the latest git release tag (last release
rem + 1 patch); a manually higher BuildInfo.VersionString in DbDo.cs
rem wins, for a deliberate minor/major bump. bumpVersion.ps1 stamps
rem DbDo.cs; syncIssVersion.ps1 (below) copies it into DbDo_setup.iss.
rem Nothing to remember beyond running this script.
if exist bumpVersion.ps1 (
    echo Bumping version from latest release tag ... >> "!log!"
    powershell -NoProfile -ExecutionPolicy Bypass -File bumpVersion.ps1 >> "!log!" 2>&1
    if errorlevel 1 echo NOTE: version bump did not run; DbDo.cs left unchanged. >> "!log!"
) else (
    echo NOTE: bumpVersion.ps1 not found; skipping version bump. >> "!log!"
)

rem ---- sync installer version from DbDo.cs (single source of truth) ----
rem buildDbDo.cmd does not own the version. DbDo.cs's
rem BuildInfo.VersionString is THE source; this step copies that value
rem into DbDo_setup.iss's #define AppVersion so the installer, the
rem uninstall entry, and the tagRelease git tag stay in lockstep with
rem the app (they had drifted to 1.0.105 while the app was at 1.0.113).
rem Non-fatal by design: if the helper or PowerShell is missing, the
rem build proceeds and the .iss is simply left as-is.
if exist syncIssVersion.ps1 (
    echo Syncing DbDo_setup.iss version from DbDo.cs ... >> "!log!"
    powershell -NoProfile -ExecutionPolicy Bypass -File syncIssVersion.ps1 >> "!log!" 2>&1
    if errorlevel 1 echo NOTE: version sync did not run; DbDo_setup.iss left unchanged. >> "!log!"
) else (
    echo NOTE: syncIssVersion.ps1 not found; skipping installer version sync. >> "!log!"
)

rem ---- locate UIA reference assemblies ----
rem v1.0.87 adds native UIA dispatch (NotificationHostControl /
rem AnnouncerProvider / UiaNative), which requires:
rem   UIAutomationProvider.dll  (IRawElementProviderSimple interface)
rem   UIAutomationTypes.dll     (AutomationNotificationKind / Processing)
rem
rem csc does not auto-resolve these from csc.rsp, so we pass them as
rem /reference: with full paths. Two probe locations, in priority order:
rem
rem   1. .NET Framework 4.8 Developer Pack reference assemblies (most
rem      machines that have csc also have these): C:\Program Files (x86)
rem      \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\.
rem      This is the recommended source -- the reference-assembly DLLs
rem      are metadata-only and what csc is designed to bind against.
rem
rem   2. GAC runtime DLLs as fallback: %WINDIR%\Microsoft.NET\assembly
rem      \GAC_MSIL\<assembly>\v4.0_4.0.0.0__31bf3856ad364e35\<assembly>.dll.
rem      Always present on Windows 10+. csc accepts them as references
rem      even though they're the actual runtime images.
rem
rem If neither source is reachable, we abort with a clear message.
set "uiaProv="
set "uiaTypes="
set "refDir=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8"
if exist "!refDir!\UIAutomationProvider.dll" set "uiaProv=!refDir!\UIAutomationProvider.dll"
if exist "!refDir!\UIAutomationTypes.dll"    set "uiaTypes=!refDir!\UIAutomationTypes.dll"

rem Fallback to .NET Framework 4.7.2 / 4.7.1 / 4.7 / 4.6.2 reference
rem assemblies if 4.8 isn't installed. The API surface for these two
rem assemblies has been stable since 4.5.
if not defined uiaProv (
    for %%v in (v4.7.2 v4.7.1 v4.7 v4.6.2 v4.6.1 v4.6 v4.5.2 v4.5.1 v4.5) do (
        if not defined uiaProv if exist "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\%%v\UIAutomationProvider.dll" set "uiaProv=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\%%v\UIAutomationProvider.dll"
        if not defined uiaTypes if exist "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\%%v\UIAutomationTypes.dll" set "uiaTypes=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\%%v\UIAutomationTypes.dll"
    )
)

rem Fallback to the GAC runtime DLLs. Always present on Windows 10+.
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll"

if not defined uiaProv (
    echo ERROR: UIAutomationProvider.dll could not be located. >> "!log!"
    echo Checked Reference Assemblies for .NET Framework 4.5 through 4.8 >> "!log!"
    echo and the .NET 4.0 GAC under %SystemRoot%\Microsoft.NET\assembly. >> "!log!"
    echo ERROR: UIAutomationProvider.dll not found. Install the .NET
    echo Framework 4.8 Developer Pack from
    echo   https://dotnet.microsoft.com/download/dotnet-framework/net48
    echo or repair .NET Framework via Settings ^> Apps.
    popd
    exit /b 1
)
if not defined uiaTypes (
    echo ERROR: UIAutomationTypes.dll could not be located. >> "!log!"
    echo Checked Reference Assemblies for .NET Framework 4.5 through 4.8 >> "!log!"
    echo and the .NET 4.0 GAC under %SystemRoot%\Microsoft.NET\assembly. >> "!log!"
    echo ERROR: UIAutomationTypes.dll not found. Install the .NET
    echo Framework 4.8 Developer Pack from
    echo   https://dotnet.microsoft.com/download/dotnet-framework/net48
    echo or repair .NET Framework via Settings ^> Apps.
    popd
    exit /b 1
)
echo UIAutomationProvider: !uiaProv! >> "!log!"
echo UIAutomationTypes:    !uiaTypes! >> "!log!"

rem ---- locate jsc.exe ----
rem jsc.exe lives only in the Framework folder; there is no Roslyn
rem JScript compiler. Prefer 64-bit, fall back to 32-bit.
set "jsc="
if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\jsc.exe" set "jsc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\jsc.exe"
if not defined jsc if exist "%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\jsc.exe" set "jsc=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\jsc.exe"

if defined jsc goto :have_jsc
echo ERROR: No jsc.exe found. >> "!log!"
echo ERROR: No jsc.exe found at %%SystemRoot%%\Microsoft.NET\Framework64\v4.0.30319\.
echo This file ships with the .NET Framework. Try repairing .NET Framework.
popd
exit /b 1

:have_jsc
echo JScript compiler: !jsc! >> "!log!"
echo Using compilers:
echo   C#:      !csc!
echo   JScript: !jsc!
echo. >> "!log!"

rem ---- fetch nvdaControllerClient.dll if missing (same as v1.0.43) ----
set "nvdaDll=nvdaControllerClient.dll"
set "nvdaUrl=https://download.nvaccess.org/releases/stable/nvda_2026.1_controllerClient.zip"
if exist "%nvdaDll%" goto :have_nvda_dll
echo Fetching %nvdaDll% ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "$tmpZip = Join-Path $env:TEMP 'nvda_controllerClient.zip';" ^
  "$tmpDir = Join-Path $env:TEMP 'nvda_controllerClient';" ^
  "if (Test-Path $tmpZip) { Remove-Item -Force $tmpZip };" ^
  "if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir };" ^
  "Invoke-WebRequest -Uri '%nvdaUrl%' -OutFile $tmpZip -UseBasicParsing;" ^
  "Expand-Archive -Path $tmpZip -DestinationPath $tmpDir;" ^
  "$x64 = Join-Path $tmpDir 'x64';" ^
  "$dll = $null;" ^
  "foreach ($n in @('nvdaControllerClient.dll', 'nvdaControllerClient64.dll')) {" ^
  "  $p = Join-Path $x64 $n;" ^
  "  if (Test-Path $p) { $dll = $p; break }" ^
  "}" ^
  "if ($null -eq $dll) {" ^
  "  $dll = Get-ChildItem -Path $tmpDir -Recurse | Where-Object { $_.Name -in @('nvdaControllerClient.dll', 'nvdaControllerClient64.dll') } | Select-Object -First 1 -ExpandProperty FullName;" ^
  "}" ^
  "if ($null -eq $dll) { throw 'nvdaControllerClient.dll (or nvdaControllerClient64.dll) not found in archive' };" ^
  "Copy-Item -Path $dll -Destination '%nvdaDll%' -Force;" ^
  "Remove-Item -Force $tmpZip;" ^
  "Remove-Item -Recurse -Force $tmpDir;" >> "!log!" 2>&1
if errorlevel 1 (
    echo WARNING: NVDA controller DLL download failed; see %log%.
    echo Manual fallback: fetch x64\nvdaControllerClient.dll from
    echo   %nvdaUrl%
    echo and place it next to DbDo.exe.
)
:have_nvda_dll

rem ---- fetch Newtonsoft.Json.dll if missing (JSON / .ipynb support) ----
rem DbDo references Newtonsoft.Json (Json.NET, MIT license) for JSON
rem import/export, and for parsing Jupyter .ipynb notebooks. The DLL is
rem pulled from nuget.org (the official NuGet flat-container URL); the
rem net45 build, which runs on .NET 4.8, is extracted next to DbDo.exe.
set "jsonDll=Newtonsoft.Json.dll"
set "jsonVer=13.0.3"
set "jsonUrl=https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.3/newtonsoft.json.13.0.3.nupkg"
if exist "%jsonDll%" goto :have_json_dll

echo Fetching %jsonDll% ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "$tmpZip = Join-Path $env:TEMP 'newtonsoft_json.zip';" ^
  "$tmpDir = Join-Path $env:TEMP 'newtonsoft_json';" ^
  "if (Test-Path $tmpZip) { Remove-Item -Force $tmpZip };" ^
  "if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir };" ^
  "Invoke-WebRequest -Uri '%jsonUrl%' -OutFile $tmpZip -UseBasicParsing;" ^
  "Expand-Archive -Path $tmpZip -DestinationPath $tmpDir;" ^
  "$dll = $null;" ^
  "foreach ($tf in @('net45','net46','net48','netstandard2.0')) {" ^
  "  $p = Join-Path $tmpDir ('lib\' + $tf + '\Newtonsoft.Json.dll');" ^
  "  if (Test-Path $p) { $dll = $p; break }" ^
  "}" ^
  "if ($null -eq $dll) {" ^
  "  $dll = Get-ChildItem -Path $tmpDir -Recurse -Filter 'Newtonsoft.Json.dll' | Select-Object -First 1 -ExpandProperty FullName;" ^
  "}" ^
  "if ($null -eq $dll) { throw 'Newtonsoft.Json.dll not found in package' };" ^
  "Copy-Item -Path $dll -Destination '%jsonDll%' -Force;" ^
  "Remove-Item -Force $tmpZip;" ^
  "Remove-Item -Recurse -Force $tmpDir;" >> "!log!" 2>&1
if errorlevel 1 (
    echo WARNING: Newtonsoft.Json download failed; see %log%.
    echo Manual fallback: download newtonsoft.json.%jsonVer%.nupkg from
    echo   https://www.nuget.org/packages/Newtonsoft.Json/%jsonVer%
    echo rename it to .zip, and copy lib\net45\Newtonsoft.Json.dll next to DbDo.exe.
)
:have_json_dll

rem ---- fetch NPOI + SharpZipLib + BouncyCastle (native .xlsx open/edit/save) ----
rem DbDo edits .xlsx via NPOI (Apache-2.0) + SharpZipLib (MIT) + BouncyCastle
rem (MIT). getDbDoDeps.ps1 downloads these managed DLLs (TLS 1.2, exact pinned
rem versions) into this folder and is idempotent. It runs AFTER the Newtonsoft
rem block on purpose: when Newtonsoft.Json.dll already exists, that blocks
rem guard does goto :have_json_dll, so anything placed before the label would be
rem skipped. The hard guard below stops the build with a clear message instead
rem of letting csc emit six CS0006 "Metadata file not found" errors.
if exist "NPOI.dll" if exist "NPOI.OOXML.dll" if exist "NPOI.OpenXml4Net.dll" if exist "NPOI.OpenXmlFormats.dll" if exist "ICSharpCode.SharpZipLib.dll" if exist "BouncyCastle.Crypto.dll" goto :have_npoi
echo Fetching NPOI 2.5.6, SharpZipLib 1.3.3, BouncyCastle 1.8.9 ...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0getDbDoDeps.ps1" >> "!log!" 2>&1
:have_npoi
set "xlsxMissing="
for %%D in (NPOI.dll NPOI.OOXML.dll NPOI.OpenXml4Net.dll NPOI.OpenXmlFormats.dll ICSharpCode.SharpZipLib.dll BouncyCastle.Crypto.dll) do if not exist "%%D" set "xlsxMissing=1"
if defined xlsxMissing (
    echo.
    echo ERROR: the NPOI .xlsx engine DLLs are missing and could not be downloaded.
    echo   getDbDoDeps.ps1 could not fetch them -- see %log% for the reason
    echo   ^(commonly no internet at build time, a proxy, or TLS/SSL blocking^).
    echo.
    echo   To fix by hand, on any PC with internet download these 3 packages,
    echo   rename each .nupkg to .zip, open it, and copy the listed DLLs into
    echo   "%CD%":
    echo     NPOI 2.5.6             lib\net45  -^> NPOI.dll, NPOI.OOXML.dll,
    echo                                         NPOI.OpenXml4Net.dll, NPOI.OpenXmlFormats.dll
    echo       https://www.nuget.org/api/v2/package/NPOI/2.5.6
    echo     SharpZipLib 1.3.3      lib\net45  -^> ICSharpCode.SharpZipLib.dll
    echo       https://www.nuget.org/api/v2/package/SharpZipLib/1.3.3
    echo     Portable.BouncyCastle  lib\net40  -^> BouncyCastle.Crypto.dll
    echo       https://www.nuget.org/api/v2/package/Portable.BouncyCastle/1.8.9
    echo   Then re-run buildDbDo.cmd.
    echo ERROR: NPOI .xlsx engine DLLs missing; aborted before compile. >> "!log!"
    exit /b 1
)


rem ---- fetch SQLean: the shell (sqlean.exe) and the extension
rem bundle (sqlean.dll) ----
rem These are TWO separate upstream projects, easy to confuse:
rem   sqlean.exe  -- the SQLite command-line shell with the SQLean
rem                  extensions built in, from nalgeon/sqlite. DbDo
rem                  shells out to it for the dot-prompt pass-through
rem                  lane, exposing the full sqlite3/SQLean shell.
rem   sqlean.dll  -- the all-in-one loadable extension bundle, from
rem                  nalgeon/sqlean (inside sqlean-win-x64.zip). DbDo
rem                  auto-loads it at connect time so REGEXP, median,
rem                  percentiles, and the rest are available to DbDo's
rem                  own connection. The init symbol sqlite3_sqlean_init
rem                  is derived from the filename, so it must stay named
rem                  sqlean.dll beside the executable.
rem Both are 64-bit, matching this x64 build. (nalgeon/sqlite is
rem archived but its release assets still download via /releases/latest.)
set "sqleanExe=sqlean.exe"
set "sqleanDll=sqlean.dll"
set "sqleanExeUrl=https://github.com/nalgeon/sqlite/releases/latest/download/sqlean.exe"
set "sqleanZipUrl=https://github.com/nalgeon/sqlean/releases/latest/download/sqlean-win-x64.zip"
if exist "%sqleanExe%" if exist "%sqleanDll%" goto :have_sqlean
echo Fetching %sqleanExe% and %sqleanDll% ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "if (-not (Test-Path '%sqleanExe%')) { Invoke-WebRequest -Uri '%sqleanExeUrl%' -OutFile '%sqleanExe%' -UseBasicParsing };" ^
  "if (-not (Test-Path '%sqleanDll%')) {" ^
  "  $tmpZip = Join-Path $env:TEMP 'sqlean_ext.zip';" ^
  "  $tmpDir = Join-Path $env:TEMP 'sqlean_ext';" ^
  "  if (Test-Path $tmpZip) { Remove-Item -Force $tmpZip };" ^
  "  if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir };" ^
  "  Invoke-WebRequest -Uri '%sqleanZipUrl%' -OutFile $tmpZip -UseBasicParsing;" ^
  "  Expand-Archive -Path $tmpZip -DestinationPath $tmpDir;" ^
  "  $dll = Get-ChildItem -Path $tmpDir -Recurse -Filter 'sqlean.dll' | Select-Object -First 1 -ExpandProperty FullName;" ^
  "  if ($null -eq $dll) { throw 'sqlean.dll not found in bundle' };" ^
  "  Copy-Item -Path $dll -Destination '%sqleanDll%' -Force;" ^
  "  Remove-Item -Force $tmpZip;" ^
  "  Remove-Item -Recurse -Force $tmpDir;" ^
  "}" >> "!log!" 2>&1
if errorlevel 1 (
    echo WARNING: SQLean download failed; see %log%.
    echo The dot-prompt shell pass-through needs sqlean.exe, and REGEXP /
    echo median / percentiles need sqlean.dll, both beside DbDo.exe. Get them at:
    echo   sqlean.exe : https://github.com/nalgeon/sqlite/releases/latest
    echo   sqlean.dll : https://github.com/nalgeon/sqlean/releases/latest  ^(sqlean-win-x64.zip^)
)
:have_sqlean

rem ---- compile DbDo.js -> DbDo.dll (JScript .NET) ----
rem
rem /target:library so the result is a DLL we can load at runtime.
rem /reference: omitted -- jsc.exe auto-resolves mscorlib, System,
rem System.Windows.Forms, etc., from the framework directory.
rem /platform:anycpu so the DLL can be loaded by either x86 or x64
rem hosts (DbDo is x64 but anycpu is the convention for class libs).
rem /out: names the assembly explicitly.
rem
rem The DLL is loaded by DbDo.exe at run time via Assembly.LoadFrom,
rem not at compile time. No /reference: to DbDo.dll is passed to
rem csc.exe below, because a same-name compile-time reference would
rem create an assembly-name collision with DbDo.exe at load time.
echo. >> "!log!"
echo Compiling DbDo.js -> DbDo.dll ... >> "!log!"
echo Compiling DbDo.js -> DbDo.dll ...
"!jsc!" /target:library /platform:anycpu /nologo /out:DbDo.dll DbDo.js >> "!log!" 2>&1
if errorlevel 1 goto :build_failed
echo DbDo.dll built.

rem ---- compile DbDo.cs -> DbDo.exe ----
rem
rem No /reference:DbDo.dll: the C# code calls DbDo.JS.runScript via
rem reflection (Assembly.LoadFrom + GetType + GetMethod), so no
rem compile-time reference is needed. Avoiding /reference: here also
rem prevents an assembly-name collision at load time, since both the
rem EXE and the snippet DLL have the simple name "DbDo".
rem
rem As of v1.0.87, csc.exe is passed explicit /reference: paths for
rem UIAutomationProvider.dll and UIAutomationTypes.dll (located above
rem and stored in !uiaProv! and !uiaTypes!). Other framework
rem references continue to auto-resolve from csc.rsp.
echo. >> "!log!"
echo Compiling DbDo.cs -> DbDo.exe ... >> "!log!"
echo Compiling DbDo.cs -> DbDo.exe ...
rem Delete any stale .exe first so a failed compile leaves no half-
rem written executable that Windows might mistake for a 16-bit binary
rem (the misleading "Unsupported 16-Bit Application" dialog appears
rem when the loader sees an empty or truncated MZ image).
if exist DbDo.exe del /f /q DbDo.exe
if exist DbDo.ico (
    "!csc!" /target:winexe /platform:x64 /optimize+ /nologo /win32icon:DbDo.ico /win32manifest:DbDo.manifest /reference:"!uiaProv!" /reference:"!uiaTypes!" /reference:"Newtonsoft.Json.dll" /reference:"Microsoft.JScript.dll" /reference:"NPOI.dll" /reference:"NPOI.OOXML.dll" /reference:"NPOI.OpenXml4Net.dll" /reference:"NPOI.OpenXmlFormats.dll" /reference:"ICSharpCode.SharpZipLib.dll" /reference:"BouncyCastle.Crypto.dll" /out:DbDo.exe Version.cs DbDo.cs >> "!log!" 2>&1
) else (
    echo NOTE: DbDo.ico not found; building without embedded icon. >> "!log!"
    "!csc!" /target:winexe /platform:x64 /optimize+ /nologo /win32manifest:DbDo.manifest /reference:"!uiaProv!" /reference:"!uiaTypes!" /reference:"Newtonsoft.Json.dll" /reference:"Microsoft.JScript.dll" /reference:"NPOI.dll" /reference:"NPOI.OOXML.dll" /reference:"NPOI.OpenXml4Net.dll" /reference:"NPOI.OpenXmlFormats.dll" /reference:"ICSharpCode.SharpZipLib.dll" /reference:"BouncyCastle.Crypto.dll" /out:DbDo.exe Version.cs DbDo.cs >> "!log!" 2>&1
)
if errorlevel 1 goto :build_failed
echo DbDo.exe built.
dir DbDo.exe | findstr DbDo.exe

rem ---- build the 2db importer in BOTH bitnesses ----
rem 2db.cs is a standalone console converter (a source data file -> a
rem standard DbDo .db shell). It is built x86 AND x64 so DbDo can bridge
rem the 32/64-bit Office ACE boundary out-of-process: DbDo runs whichever
rem build matches the installed Office (and falls back to the other on a
rem provider-unavailable exit code). /target:exe (console) so the importer
rem can prompt and report on stdout/stderr. Microsoft.CSharp (for the
rem dynamic COM calls) auto-resolves from csc.rsp, as it does for DbDo.cs.
if not exist 2db.cs goto :skip_2db
echo. >> "!log!"
echo Compiling 2db.cs -^> 2db32.exe and 2db64.exe ... >> "!log!"
echo Compiling 2db.cs -^> 2db32.exe and 2db64.exe ...
if exist 2db32.exe del /f /q 2db32.exe
if exist 2db64.exe del /f /q 2db64.exe
"!csc!" /target:exe /platform:x86 /optimize+ /nologo /out:2db32.exe 2db.cs >> "!log!" 2>&1
if errorlevel 1 goto :build_failed
"!csc!" /target:exe /platform:x64 /optimize+ /nologo /out:2db64.exe 2db.cs >> "!log!" 2>&1
if errorlevel 1 goto :build_failed
echo 2db32.exe and 2db64.exe built.
dir 2db32.exe | findstr 2db32.exe
dir 2db64.exe | findstr 2db64.exe
goto :have_2db
:skip_2db
rem 2db.cs is optional, forward-looking infrastructure (a planned
rem out-of-process importer that would bridge the 32/64-bit Office ACE
rem boundary). It is not part of the current build: DbDo uses its
rem native readers and does not invoke 2db32/64.exe. When 2db.cs is
rem absent we skip it silently; drop a 2db.cs in this folder to build it.
:have_2db


rem ---- generate HTML documentation ----
echo. >> "!log!"
echo Generating HTML documentation ... >> "!log!"
where pandoc >nul 2>&1
if errorlevel 1 goto :no_pandoc
pandoc --standalone --toc --toc-depth=3 --metadata=title:"DbDo User Guide" -o DbDo.htm DbDo.md >> "!log!" 2>&1
pandoc --standalone --toc --toc-depth=3 --metadata=title:"DbDo README" -o README.htm README.md >> "!log!" 2>&1
goto :doc_done
:no_pandoc
echo WARNING: pandoc not found on PATH. Install with: winget install JohnMacFarlane.Pandoc

:doc_done
echo.
echo Build complete. Artifacts in this directory:
echo   DbDo.exe       -- the application
echo   DbDo.dll       -- JScript .NET scripting support
echo   nvdaControllerClient.dll -- NVDA controller-client DLL
echo   Newtonsoft.Json.dll -- JSON (Json.NET) support
echo   sqlean.exe -- SQLite/SQLean shell for the dot-prompt pass-through lane
echo   sqlean.dll -- SQLean extension bundle (REGEXP, median, percentiles, ...)
if exist 2db64.exe echo   2db32.exe / 2db64.exe -- standalone importer (32- and 64-bit) for the Import command
popd
endlocal
exit /b 0

:build_failed
echo. >> "!log!"
echo BUILD FAILED. See %log% for details.
type "!log!" | findstr /C:"error" /C:"Error" /C:"FAILED"
popd
endlocal
exit /b 1
